### ISSUE TITLE
Object of type Device is not JSON serializable

### ISSUE THREAD

**Issue by bakman2** [tetienne/somfy-open-api#45]
Using Connexoon IO
Trying to dump the devices:

```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    dumps = json.dumps(devices, sort_keys=True, indent=4, separators=(',', ': '))
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Device is not JSON serializable
```

when dumping devices with pprint

```
[<pymfy.api.model.Device object at 0x7fc847fd1f48>,
 <pymfy.api.model.Device object at 0x7fc847fd1fa8>]
```
How do i determine what my device is (single blinds)

**Comment by tetienne** [comment]
Can you please share your full code sample?

**Comment by bakman2** [comment]
Sure, from your readme

```
import json
import re
from urllib.parse import urlparse, parse_qs

client_id = r'<CLIENT_ID>' # Consumer Key
redir_url = '<REDIR_URL>' # Callback URL (for testing, can be anything)
secret = r'<secret>' # Consumer Secret

from pymfy.api.somfy_api import SomfyApi

api = SomfyApi(client_id, secret, redir_url)
authorization_url, _ = api.get_authorization_url()
print('Please go to {} and authorize access.'.format(authorization_url))
authorization_response = input('Enter the full callback URL')
code = parse_qs(urlparse(authorization_response).query)['code'][0]
api.request_token(code=code)

devices = api.get_devices()
# Remove personal information
dumps = json.dumps(devices, sort_keys=True, indent=4, separators=(',', ': '))
dumps = re.sub('".*id.*": ".*",\n', '', dumps)

print(dumps)
```
(with correct credentials ofcourse).

**Comment by tetienne** [comment]
Oh indeed Device is no more JSON serializable. README must be updated. Sorry for that. 

To see the device returned by the API you can do this
```python
#...
devices = api.get_devices()
for device in devices:
  print(f"Name:{device.name}, Category: {device.categories}, Type: {device.type}"
```

If you want to retrieve only your blind, you can do:

```python
devices = api.get_devices(category=Category.ROLLER_SHUTTER)

covers = [RollerShutter(d, api) for d in devices]

# Open all the covers
for cover in covers:
  cover.open()
```

**Comment by bakman2** [comment]
Thanks that works

```
Name:MAESTRIA+ io, Category: ['actuator', 'exterior_blind'], Type: exterior_blind_positionable_stateful_generic
Name:CONNEXOON, Category: ['hub'], Type: hub_connexoon
```

I assume that `category=Category.ROLLER_SHUTTER` should be `Category.exterior_blind` ?

**Comment by tetienne** [comment]
You are right. You can see the category enum here: https://github.com/tetienne/somfy-open-api/blob/master/pymfy/api/devices/category.py
